### Pobierz wszystkie wycieczki
GET https://localhost:7115/api/trips
Accept: application/json

###

### Dodaj nowego klienta
POST https://localhost:7115/api/clients
Content-Type: application/json

{
  "firstName": "Jan",
  "lastName": "Kowalski",
  "email": "jan.kowalski@example.com",
  "telephone": "123456789",
  "pesel": "12345678901"
}
